---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8scontroller-sentinel
  namespace: mon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8scontroller-sentinel
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: [get, watch, list]
- apiGroups: ['']
  resources: [pods]
  verbs: [get, watch, list, delete]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8scontroller-sentinel
subjects:
- kind: ServiceAccount
  name: k8scontroller-sentinel
  namespace: mon
roleRef:
  kind: ClusterRole
  name: k8scontroller-sentinel
  apiGroup: rbac.authorization.k8s.io
